# Generated by Django 5.0.3 on 2024-10-14 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome_do_aluno', models.CharField(max_length=150)),
                ('sala', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='Nicho',
            fields=[
                ('id_nicho', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_nicho', models.PositiveIntegerField()),
                ('local', models.CharField(max_length=100, null=True)),
                ('observacao', models.TextField(null=True)),
            ],
            options={
                'db_table': 'nicho',
            },
        ),
        migrations.CreateModel(
            name='Professor_Funcionario',
            fields=[
                ('id_professor_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_do_professor_funcionario', models.CharField(max_length=150)),
                ('ocupacao', models.CharField(choices=[('Professor', 'Professor'), ('Funcionario', 'Funcionário')], default='Professor', max_length=20)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'professor_funcionario',
            },
        ),
        migrations.CreateModel(
            name='StatusEmprestimo',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Emprestado', 'Emprestado'), ('Devolvido', 'Devolvido'), ('Extraviado', 'Extraviado'), ('Reservado', 'Reservado'), ('Aguardando_retirada', 'Aguardando Retirada'), ('Em_processamento', 'Em Processamento'), ('Vencido', 'Vencido'), ('Renovado', 'Renovado'), ('Danificado', 'Danificado'), ('Em_analise', 'Em Análise'), ('Cancelado', 'Cancelado')], max_length=20)),
            ],
            options={
                'db_table': 'statusemprestimo',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id_emprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_devolucao', models.DateField()),
                ('situacao_emprestimo', models.CharField(choices=[('Aberto', 'Aberto'), ('Concluido', 'Concluido')], default='Aberto', max_length=20)),
                ('id_usuario_aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_aluno', to='biblioteca.aluno')),
                ('id_usuario_professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_professor', to='biblioteca.professor_funcionario')),
            ],
            options={
                'db_table': 'emprestimo',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('nome_do_livro', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('quantidade_exemplar', models.IntegerField()),
                ('saldo_exemplar', models.IntegerField()),
                ('observacao_livro', models.TextField(null=True)),
                ('id_nicho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.nicho')),
            ],
            options={
                'db_table': 'livro',
            },
        ),
        migrations.CreateModel(
            name='ReservaLivro',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(max_length=150)),
                ('sala', models.CharField(max_length=15)),
                ('data_reserva', models.DateField(auto_now_add=True)),
                ('livro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro')),
            ],
            options={
                'db_table': 'reserva_livro',
            },
        ),
        migrations.CreateModel(
            name='SugestaoLivro',
            fields=[
                ('id_sugestao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=150)),
                ('sala', models.CharField(max_length=15)),
                ('periodo', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_autor', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo_livro', models.CharField(max_length=255)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.aluno')),
            ],
            options={
                'db_table': 'sugestao_livro',
            },
        ),
        migrations.CreateModel(
            name='LivroEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('id_emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.emprestimo')),
                ('id_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro')),
                ('id_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.statusemprestimo')),
            ],
            options={
                'db_table': 'livro_emprestimo',
                'unique_together': {('id_livro', 'id_emprestimo')},
            },
        ),
    ]
