"""
Django settings for drp03_pi project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
import dj_database_url  # Database configuration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3jfg-zccyiz3o6gi^kb*_p+=d3_os8aw48qo-xf7bx&_qwt60e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    #'gerenciadorfrontend1-3e87d894f0d5.herokuapp.com',
    'bibliotecayolanda.rj.r.appspot.com',
    'gerenciadorbiblioteca.rj.r.appspot.com',
    #'gerenciadordebibliotecaback-08343971641b.herokuapp.com',
    'localhost',
    '127.0.0.1'
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'biblioteca',
    'rest_framework',
    'rest_framework.authtoken',  # Tentativa 27/09/2024
    'bootstrap4',
    'stdimage',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    'https://bibliotecayolanda.rj.r.appspot.com',
    'http://bibliotecayolanda.rj.r.appspot.com',
    'https://gerenciadorbiblioteca.rj.r.appspot.com',
    'http://gerenciadorbiblioteca.rj.r.appspot.com',
    #'bibliotecayolanda.rj.r.appspot.com',
    #'gerenciadorbiblioteca.rj.r.appspot.com',
    #"https://gerenciadorfrontend1-3e87d894f0d5.herokuapp.com",
    #"https://gerenciadordebibliotecaback-08343971641b.herokuapp.com"
]

CORS_ALLOW_CREDENTIALS = True

# Configurações de segurança relacionadas a CSRF

SESSION_COOKIE_SECURE = True  # Garante que os cookies de sessão só sejam enviados em conexões HTTPS
CSRF_COOKIE_SECURE = True     # Garante que o cookie CSRF só seja enviado em conexões HTTPS
CSRF_COOKIE_SAMESITE = 'None' # Permite que o cookie CSRF seja enviado em requisições cross-site (necessário para alguns cenários)



#CSRF_TRUSTED_ORIGINS = ['https://gerenciadorfrontend1-3e87d894f0d5.herokuapp.com']
CSRF_TRUSTED_ORIGINS = [
    'https://bibliotecayolanda.rj.r.appspot.com',
    'http://bibliotecayolanda.rj.r.appspot.com',
    'https://gerenciadorbiblioteca.rj.r.appspot.com',
    'http://gerenciadorbiblioteca.rj.r.appspot.com',
]
# CORS_ALLOW_ALL_ORIGINS = True  # Tentativa 27/09/2024

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

ROOT_URLCONF = 'drp03_pi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drp03_pi.wsgi.application'

# Database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Define o backend como SQLite
        'NAME': BASE_DIR / 'db.sqlite3',  # Define o caminho do arquivo do banco de dados SQLite
    }
}

"""
DATABASES = {
    'default': dj_database_url.config(
        default='postgres://u1mo67fo8ml5fv:p3b76eb86641d390eca0bf43194f382591865afa38d3ae1c2311473b85eed1f76@c3nv2ev86aje4j.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com/d7k62u2hgpd0jp',
        conn_max_age=600,
        ssl_require=True
    )
}
"""
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

LOGIN_REDIRECT_URL = '/principal/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


