# Generated by Django 5.0.3 on 2024-05-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('nome_do_usuario', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='data_registro',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='ra',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='tipo_aluno',
        ),
        migrations.RemoveField(
            model_name='professor_funcionario',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='professor_funcionario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='professor_funcionario',
            name='data_registro',
        ),
        migrations.RemoveField(
            model_name='professor_funcionario',
            name='tipo_professor_funcionario',
        ),
        migrations.AddField(
            model_name='aluno',
            name='sala',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='professor_funcionario',
            name='ocupacao',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='situacao_emprestimo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='professor_funcionario',
            name='nome_do_professor_funcionario',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='professor_funcionario',
            name='telefone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
