# Generated by Django 5.0.3 on 2024-05-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('nome_do_usuario', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
                ('data_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
