# Generated by Django 5.0.3 on 2024-11-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservalivro',
            name='aluno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservalivro',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservalivro',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
