# Generated by Django 5.0.3 on 2024-05-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='situacao_emprestimo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='professor_funcionario',
            name='nome_do_professor_funcionario',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='professor_funcionario',
            name='telefone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
