# Generated by Django 5.0.3 on 2024-05-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor_funcionario',
            old_name='tipo_professor_funcionario',
            new_name='ocupacao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='data_registro',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='ra',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='tipo_aluno',
        ),
        migrations.RemoveField(
            model_name='professor_funcionario',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='professor_funcionario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='professor_funcionario',
            name='data_registro',
        ),
        migrations.AddField(
            model_name='aluno',
            name='sala',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
