# Generated by Django 5.0.3 on 2024-05-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_remove_aluno_ativo_remove_aluno_data_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='data_registro',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='ra',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='tipo_aluno',
        ),
        migrations.RemoveField(
            model_name='professor_funcionario',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='professor_funcionario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='professor_funcionario',
            name='data_registro',
        ),
        migrations.RemoveField(
            model_name='professor_funcionario',
            name='tipo_professor_funcionario',
        ),
        migrations.AddField(
            model_name='aluno',
            name='sala',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='professor_funcionario',
            name='ocupacao',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
