# Generated by Django 5.0.3 on 2024-05-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_rename_tipo_professor_funcionario_professor_funcionario_ocupacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='situacao_emprestimo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='professor_funcionario',
            name='ocupacao',
            field=models.CharField(max_length=40),
        ),
    ]
