# Generated by Django 5.0.3 on 2024-05-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_login_alter_emprestimo_situacao_emprestimo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='nome_usuario',
            new_name='nome_do_usuario',
        ),
    ]
