# Generated by Django 5.0.3 on 2024-11-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_reservalivro_aluno_reservalivro_email_and_more'),
        ('biblioteca', '0008_reservalivro_sugestaolivro'),
    ]

    operations = [
    ]
